### ISSUE TITLE
Replace black with ruff formatter

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#101]
In https://github.com/jaraco/pip-run/commit/850cf7c94447a1570daa17cc25f108b26b63eca2, I've started experimenting with what it will take to replace black with ruff formatter.

Basically, pytest-ruff already supports enforcement with the `--ruff-format` option, and with the following config, 

```ruff.toml
[format]
preview = true
quote-style = "preserve"
```

It's pretty comparable to the current black style.

#99 already starts to explore this change.

There are a few things that still need to be addressed:

_Should the change introduce import sorting and pyupgrade also?_

My instinct is no, let's start with something that's essentially comparable to black and later expand the scope.

_Should `--ruff-format` be added to each and every project or to `pytest-enabler`?_

My instinct is it should be in `pytest-enabler`, comparable to the black behavior. That's a little complicated because it's a backward-incompatible change and for users with both pytest-ruff and pytest-black installed, it might produce irreconcilable failures.

I'd say we should take it one step at a time, except that introducing it for all projects and then later changing the default for `pytest-enabler` will result in a lot of flux in `pyproject.toml` for all projects (along with the possible merge conflicts).

**Comment by bswck** [comment]
Based! 🚀

**Comment by jaraco** [comment]
While rolling this out, I've learned that the removal of the black badge triggers merge conflicts due to changes in the subsequent RTD badge (when it's been enabled downstream). The jaraco.develop routine that resolves the conflict ends up discarding the downstream change (causing the RTD badge to be commented out again if it had been uncommented).

**Comment by jaraco** [comment]
This is what the conflict looks like unresolved:

```diff
 path main @ git diff
diff --cc README.rst
index c8f71e1,2fabcf3..0000000
--- a/README.rst
+++ b/README.rst
@@@ -11,12 -11,8 +11,17 @@@
      :target: https://github.com/astral-sh/ruff
      :alt: Ruff
  
++<<<<<<< HEAD
 +.. image:: https://img.shields.io/badge/code%20style-black-000000.svg
 +   :target: https://github.com/psf/black
 +   :alt: Code style: Black
 +
 +.. image:: https://readthedocs.org/projects/path/badge/?version=latest
 +   :target: https://path.readthedocs.io/en/latest/?badge=latest
++=======
+ .. .. image:: https://readthedocs.org/projects/PROJECT_RTD/badge/?version=latest
+ ..    :target: https://PROJECT_RTD.readthedocs.io/en/latest/?badge=latest
++>>>>>>> b8c6c1530ef937521b60aabb0ecd98a8b5dca761
  
  .. image:: https://img.shields.io/badge/skeleton-2023-informational
     :target: https://blog.jaraco.com/skeleton
```
