### ISSUE TITLE
macOS failing on Python 3.8

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#124]
Recently, CI jobs started failing for macOS on Python 3.8:

>   Version ~3.8.0-0 was not found in the local cache
>   Error: The version '3.8' with architecture 'arm64' was not found for macOS 14.4.1.
>  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Comment by jaraco** [comment]
Maybe related: https://github.com/actions/setup-python/issues/808

**Comment by jaraco** [comment]
That links to https://github.com/actions/setup-python/issues/850, definitely relevant.

**Comment by jaraco** [comment]
I've opted to just suppress the failure. I'm disinclined to spend time and energy revamping the matrix to support more Pythons. If it's not important enough for GitHub to cover the combination, it's not important enough for me and my projects. I'll just spot-check macos on Python 3.8 as needed.

**Comment by bswck** [comment]
See also https://github.com/actions/setup-python/issues/696.
