### ISSUE TITLE
Update for Python 3.13

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#141]
It's that time. Python 3.13 is in RC. Let's get all of the test suites running 3.13.

Before we do that, there are probably some projects where CI is failing currently or where merging the most recent changes causes them to fail. Let's get them all passing before bumping the Python version.

**Comment by bswck** [comment]
@jaraco for the future, do you think it's a good idea to also test against prereleased Python for more seamless updates of minor versions?

That is, test against 3.13 along with 3.14-dev.

**Comment by jaraco** [comment]
In my experience, adopting dev versions early causes too much disruption. Anything that depends on lxml or pyobjc or other binary packages usually doesn't get a wheel build until very late and often doesn't fix compiler errors until late in the beta cycle. I'm hoping by now some of those packages have wheels or at least have worked out the kinks so those packages build on those platforms.

At one point, I'd added in 3.13 with the jobs allowed to fail. Maybe we could do something like that... depending on how much disruption it causes.

**Comment by jaraco** [comment]
Done in #146
