### ISSUE TITLE
Widespread mypy failures

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#143]
As mentioned in https://github.com/jaraco/skeleton/pull/136#issuecomment-2303511967 and https://github.com/jaraco/skeleton/pull/142#issuecomment-2308742608, I'm trying to figure out a strategy for incorporating stricter settings for mypy without incurring too much toil.

Right now, about half of the [projects](https://www.jaraco.com/projects) are failing:

![image](https://github.com/user-attachments/assets/2dcc5f1c-6063-4a5f-98db-797bc6614367)

- [ ] jaraco.collections
- [ ] jaraco.compat
- [ ] jaraco.context
- [ ] jaraco.crypto
- [ ] jaraco.desktop
- [ ] jaraco.email
- [ ] jaraco.fabric
- [ ] jaraco.financial
- [ ] jaraco.functools
- [ ] jaraco.home
- [ ] jaraco.imaging
- [ ] jaraco.input
- [ ] jaraco.logging
- [ ] jaraco.media
- [ ] jaraco.modb
- [ ] jaraco.mongodb
- [ ] jaraco.net
- [ ] jaraco.nxt
- [ ] jaraco.office
- [ ] jaraco.parables
- [ ] jaraco.pmxbot
- [ ] jaraco.postgres
- [ ] jaraco.services
- [ ] jaraco.site
- [ ] jaraco.test
- [ ] jaraco.text
- [ ] jaraco.tidelift
- [ ] jaraco.translate
- [ ] jaraco.ui
- [ ] jaraco.util
- [ ] jaraco.vcs
- [ ] jaraco.windows
- [ ] jaraco.xkcd
- [ ] keyrings.alt
- [ ] keyrings.firefox
- [ ] lpaste
- [ ] nat-pmp
- [ ] nspektr
- [ ] openpack
- [ ] paradocx
- [ ] path
- [ ] pip-run
- [ ] pmxbot.webhooks
- [ ] pytest-checkdocs
- [ ] pytest-enabler
- [ ] pytest-perf
- [ ] recapturedocs
- [ ] rst.linker
- [ ] singledispatch
- [ ] svg.charts
- [ ] tempora
- [ ] treehouse
- [ ] xlsxcessive

**Comment by jaraco** [comment]
I was hoping there might be a way to treat failures as warnings, but I couldn't find such a feature, so I filed https://github.com/realpython/pytest-mypy/issues/177. In the meantime, I think we should disable mypy checks until these issues can be addressed.

**Comment by jaraco** [comment]
I've rolled out d3e83be to all the projects. Let's see if that clears some things up. In the meantime, I welcome anyone to help out submitting PRs to the individual projects above such that `tox -- --mypy` passes.

**Comment by Avasam** [comment]
> I was hoping there might be a way to treat failures as warnings, but I couldn't find such a feature, so I filed [realpython/pytest-mypy#177](https://github.com/realpython/pytest-mypy/issues/177). In the meantime, I think we should disable mypy checks until these issues can be addressed.

mypy warnings would be nice, and probably the best solution.

**Comment by Avasam** [comment]
And done !
