### ISSUE TITLE
No support for linking usernames

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#144]
In https://github.com/jaraco/jaraco.collections/pull/16, the author referenced themselves in the news fragment, but that caused the [release to fail](https://github.com/jaraco/jaraco.collections/actions/runs/10548977750/job/29223489125) (late, only after finalizing the release).

They got the impression they could use this syntax because it was contributed downstream to Setuptools but not to other projects.

We should probably add support for that in all skeleton and coherent projects.

Of course, the way it's implemented is not sustainable because the [config requires hard-coded values](https://github.com/pypa/setuptools/blob/67b35f2f44c8aa290b4377ab98ff59384e91b0c4/docs/conf.py#L120-L131).

**Comment by Avasam** [comment]
Oh darn, I've been doing the same for other newly typed skeleton-based projects.

I don't suppose any of this could be pulled from git data when building docs? (idk if the project is checked out just copied)

**Comment by jaraco** [comment]
Oh! Great observation. Yes, that should be trivial to add. I'll do that.

**Comment by jaraco** [comment]
I'm wondering which is best - `github.com/{username}` or `github.com/sponsors/{username}`. My instinct would be to simply link to the user, and let a potential sponsor traverse to the sponsors page if appropriate. It feels a little sketchy to drive users to the sponsors URL when all they're doing is clicking on the "user". After musing about it for a moment, I think I prefer the non-sponsors page. Let's go with that for now until someone else is willing to make the case for the sponsors page.

**Comment by Avasam** [comment]
It's also odd if there user hasn't setup sponsors. I'm in favor of linking to the profile page as well.
