### ISSUE TITLE
Latest version of `ruff` is pulled into tests but clashes with version in `.pre-commit-hooks.yaml`

### ISSUE THREAD

**Issue by abravalheri** [jaraco/skeleton#149]
This means that while we need to reformat some files to satisfy `pytest-ruff`, the `pre-commit` hook will not allow these changes to be committed.

The suggested solution is to bump the `pre-commit` hook.

**Comment by Avasam** [comment]
Given pre-commit.ci isn't even used, I really feel like this is just maintenance burden (https://github.com/jaraco/skeleton/issues/109#issuecomment-2278690175). A [tox?] autofixing script/command would be just as useful locally, so this is just a nice to have for those who want to run the python "pre-commit" tool as a git pre-commit hook. Even then, you could either:
A) Let users configure their own hook with w/e tool they want. If it needs a custom config file (like `.pre-commit-config.yaml`), they can gitignore it like any other environment-specific file that the project doesn't make special use of.
B) The skeleton can provide a simple "local repo" hook that calls said autofixing command. Just as a welcome convenience for those who want to use the pre-commit tool as a git hook.

Even if you want to include CI autofixes at some point, my linked comment offers two alternatives that don't require keeping a duplicate list of dependencies in sync and doesn't require pinning to an exact version.
