### ISSUE TITLE
Ruff misconfiguration

### ISSUE THREAD

**Issue by abravalheri** [jaraco/skeleton#152]
Right now, if I try to run `pipx run --python python3.12 ruff check` on the setuptools codebase I get the following error:

```
ruff failed
  Cause: Failed to parse /home/abravalheri/workspace/setuptools/ruff.toml
  Cause: TOML parse error at line 2, column 11
  |
2 | include = "pyproject.toml"
  |           ^^^^^^^^^^^^^^^^
invalid type: string "pyproject.toml", expected a sequence

```

The same error shows up in `skeleton`'s CI: https://github.com/jaraco/skeleton/actions/runs/11558298719/job/32170335213.

Probably it should be `include = ["pyproject.toml"]`?

The configuration was introduced in https://github.com/jaraco/skeleton/commit/e61a9df7cdc9c8d1b56c30b7b3f94a7cdac14414.

**Comment by abravalheri** [comment]
According to @Avasam in https://github.com/pypa/setuptools/pull/4718#issuecomment-2448099867, even if we fix the "syntax" of the  `include` field, the presence of it still cause other problems.

Another temporary, workaround while https://github.com/astral-sh/ruff/issues/10299 is not handled is to explicitly use `target-version = "py39" # Target the oldest supported Python version` as pointed out in the comment linked above.

**Comment by jaraco** [comment]
Looking at #119, I think I confused myself and it should have been "extend" and not "include".

**Comment by jaraco** [comment]
Sorry for the disruption

**Comment by Avasam** [comment]
> Looking at #119, I think I confused myself and it should have been "extend" and not "include".

Oh wow, I didn't catch on either... Of course Ruff shows no error if you only include a non-python file >.<
