### ISSUE TITLE
Fail on warnings in docs builds

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#29]
The Setuptools project has relied on the `-W` option to sphinx-build ([docs](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#options)) to ensure that warnings aren't perpetually ignored. That seems like a worthy non-default to apply.

**Comment by webknjaz** [comment]
Also, add `-n` because I'm not sure that having it on in `conf.py` has the same effect.
