### ISSUE TITLE
Colorize Sphinx output

### ISSUE THREAD

**Issue by webknjaz** [jaraco/skeleton#31]
Some CIs don't expose enough information for tools to decide whether they support ANSI-sequences while it's experimentally proven that they do. TBH most of the existing envs support this. In such cases, we need to explicitly tell the tools to output the color markers.
For Sphinx, this essentially means adding `--color` when invoking it. I think this should be a part of the skeleton.

**Comment by jaraco** [comment]
Can you explain more? Looking at [the docs](https://www.sphinx-doc.org/en/master/man/sphinx-build.html), I see `-N` for disabling color but nothing for enabling color. Is `--color` an undocumented feature that forces color for when support fails to be autodetected?

**Comment by webknjaz** [comment]
Yes. It looks like the docs web page doesn't mention it, but running `--help` has it documented:
```console
$ python -m sphinx --help 
[...]
  --color           do emit colored output (default: auto-detect)
  -N, --no-color    do not emit colored output (default: auto-detect)
[...]
```

**Comment by webknjaz** [comment]
@jaraco also, shouldn't there be a `passenv` in `tox.ini` for this to work?

**Comment by webknjaz** [comment]
Found that PR I was trying to remember. It seemed to be `colorama`'s fault: https://github.com/tartley/colorama/pull/230.

Though when I dag deeper, it turned out Sphinx only uses it under Windows.
