### ISSUE TITLE
Enable PR builds in RTD in every project

### ISSUE THREAD

**Issue by webknjaz** [jaraco/skeleton#41]
There's now an API for this: https://github.com/readthedocs/readthedocs.org/pull/7834.

This seems to be available via [`PATCH /api/v3/projects/(string:project_slug)/`](https://docs.readthedocs.io/en/stable/api/v3.html#patch--api-v3-projects-(string-project_slug)-).

**Comment by jaraco** [comment]
I'd like if someone could write a routine that logs into RTD, finds all the projects, and turns this on for each one.

**Comment by jaraco** [comment]
In jaraco.develop, I've been working on routines for running routines across a list of projects (https://github.com/jaraco/jaraco.develop/blob/f23616fb13b2b8c17a96b185600fdc08ec7d18c2/jaraco/develop/git.py#L174-L179). Next, we'll need someone to go through that list, figure out which of those projects need the treatment, determine which of them already have the treatment, and apply the treatment to the remainder. It looks like the project slug is something that will need to be derived from the project name.

Is patching the `external_builds_enabled` the only setting that needs to be changed?

**Comment by jaraco** [comment]
In https://github.com/jaraco/jaraco.develop/commit/8553b77559266132b2746b4c2c1d2058bd9e1c87, I added a routine to enable the PR builds and I ran it with

```json
>>> import jaraco.develop.rtd as rtd
>>> rtd.enable_pr_build('jaraco.collections')
```

The routine ran without error, but the setting was unchanged in RTD:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/308610/229391739-b38bc425-41ae-471b-96cf-cf44900bf41f.png">

Despite having patched, I don't see that value in the project:

```
 draft $ http --body https://readthedocs.org/api/v3/projects/jaracocollections/ Authorization:@(auth)
{
    "_links": {
        "_self": "https://readthedocs.org/api/v3/projects/jaracocollections/",
        "builds": "https://readthedocs.org/api/v3/projects/jaracocollections/builds/",
        "environmentvariables": "https://readthedocs.org/api/v3/projects/jaracocollections/environmentvariables/",
        "redirects": "https://readthedocs.org/api/v3/projects/jaracocollections/redirects/",
        "subprojects": "https://readthedocs.org/api/v3/projects/jaracocollections/subprojects/",
        "superproject": "https://readthedocs.org/api/v3/projects/jaracocollections/superproject/",
        "translations": "https://readthedocs.org/api/v3/projects/jaracocollections/translations/",
        "versions": "https://readthedocs.org/api/v3/projects/jaracocollections/versions/"
    },
    "created": "2017-10-25T18:38:27.962115Z",
    "default_branch": "main",
    "default_version": "latest",
    "homepage": null,
    "id": 154953,
    "language": {
        "code": "en",
        "name": "English"
    },
    "modified": "2020-12-28T01:06:58.081797Z",
    "name": "jaraco.collections",
    "programming_language": {
        "code": "py",
        "name": "Python"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/jaraco/jaraco.collections.git"
    },
    "slug": "jaracocollections",
    "subproject_of": null,
    "tags": [],
    "translation_of": null,
    "urls": {
        "builds": "https://readthedocs.org/projects/jaracocollections/builds/",
        "documentation": "https://jaracocollections.readthedocs.io/en/latest/",
        "home": "https://readthedocs.org/projects/jaracocollections/",
        "versions": "https://readthedocs.org/projects/jaracocollections/versions/"
    },
    "users": [
        {
            "username": "jaraco"
        }
    ]
}
```

**Comment by jaraco** [comment]
I changed the value manually in the RTD UI, and that caused the 'modified' date to change in the config, but there's still nothing there about `external_builds_enabled`. I don't think the API works as advertised. I'm not interested enough in this issue to solve it in other systems and since no one else has done any work on this, I'm giving up.
