### ISSUE TITLE
Warning in docs build when invoked with sphinx-build

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#59]
Only one small details still is to resolve.
In mean time Iime moved away from using sphinx<>setuptools integration on generate documentation to straight use `spinx-build`.
On using that command I see one warning:
```console
[tkloczko@devel-g2v jaraco.tidelift-1.5.0]$ SETUPTOOLS_SCM_PRETEND_VERSION=1.5.0 /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index
WARNING: autodoc: failed to import module 'tidelift' from module 'jaraco'; the following exception was raised:
No module named 'jaraco.tidelift'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-jaraco-tidelift.3 { history } done
build succeeded, 1 warning.

The manual pages are in build/sphinx/man.
```
This can be fixed by patch like below:
```patch
--- a/docs/conf.py~     2022-04-22 01:50:53.000000000 +0000
+++ b/docs/conf.py      2022-04-22 01:51:50.045055143 +0000
@@ -1,6 +1,10 @@
 #!/usr/bin/env python3
 # -*- coding: utf-8 -*-

+import sys
+import os
+sys.path.insert(0, os.path.abspath('..'))
+
 extensions = ['sphinx.ext.autodoc', 'jaraco.packaging.sphinx', 'rst.linker']

 master_doc = "index"
```
With that patch:
```console
[tkloczko@devel-g2v jaraco.tidelift-1.5.0]$ SETUPTOOLS_SCM_PRETEND_VERSION=1.5.0 /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-jaraco-tidelift.3 { history } done
build succeeded.

The manual pages are in build/sphinx/man.
```
Such modification is even suggested in template copy.py example https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file

Feel free to close that ticket and commit that change or let me know if you want me to submit it as PR.

_Originally posted by @kloczek in https://github.com/jaraco/jaraco.tidelift/issues/4#issuecomment-1105927535_

**Comment by jaraco** [comment]
The issue doesn't occur when building docs using the tox environment:

<details>

```
jaraco.tidelift main $ tox -e docs
docs create: /Users/jaraco/code/main/jaraco.tidelift/.tox/docs
docs develop-inst: /Users/jaraco/code/main/jaraco.tidelift
docs installed: alabaster==0.7.12,attrs==21.4.0,autocommand==2.2.1,Babel==2.10.1,black==22.3.0,certifi==2021.10.8,charset-normalizer==2.0.12,click==8.1.2,coverage==6.3.2,docutils==0.17.1,filelock==3.6.0,flake8==4.0.1,idna==3.3,imagesize==1.3.0,importlib-metadata==4.11.3,importlib-resources==5.7.1,iniconfig==1.1.1,jaraco.context==4.1.1,jaraco.functools==3.5.0,jaraco.packaging==9.0.0,-e git+gh://jaraco/jaraco.tidelift@97b83c0b011faa08eaf62b9a1f09ded2e86b622e#egg=jaraco.tidelift,Jinja2==3.1.1,keyring==23.5.0,MarkupSafe==2.1.1,mccabe==0.6.1,more-itertools==8.12.0,mypy==0.942,mypy-extensions==0.4.3,packaging==21.3,pathspec==0.9.0,pep517==0.12.0,platformdirs==2.5.2,pluggy==1.0.0,py==1.11.0,pycodestyle==2.8.0,pyflakes==2.4.0,Pygments==2.11.2,pyparsing==3.0.8,pytest==7.1.1,pytest-black==0.3.12,pytest-checkdocs==2.7.1,pytest-cov==3.0.0,pytest-enabler==1.2.1,pytest-flake8==1.1.1,pytest-mypy==0.9.1,python-dateutil==2.8.2,pytz==2022.1,requests==2.27.1,requests-toolbelt==0.9.1,rst.linker==2.3.0,six==1.16.0,snowballstemmer==2.2.0,Sphinx==4.5.0,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,toml==0.10.2,tomli==2.0.1,types-docutils==0.18.3,typing_extensions==4.2.0,urllib3==1.26.9,zipp==3.8.0
docs run-test-pre: PYTHONHASHSEED='227064748'
docs run-test: commands[0] | python -m sphinx -W --keep-going . /Users/jaraco/code/main/jaraco.tidelift/build/html
Running Sphinx v4.5.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [ 50%] history
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 50%] history
writing output... [100%] index

generating indices... genindex py-modindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in ../build/html.
___________________________________________________________________ summary ___________________________________________________________________
  docs: commands succeeded
  congratulations :)
```
</details>

Nor does it happen when [building under readthedocs](https://readthedocs.org/projects/jaracofunctools/builds/15578667/).

I can replicate the issue thus:

```
jaraco.tidelift main $ .tox/docs/bin/pip uninstall -y -q jaraco.tidelift
jaraco.tidelift main $ .tox/docs/bin/sphinx-build docs build/sphinx/html
Running Sphinx v4.5.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                
WARNING: autodoc: failed to import module 'tidelift' from module 'jaraco'; the following exception was raised:
No module named 'jaraco.tidelift'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                 
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 1 warning.

The HTML pages are in build/sphinx/html.
```

The issue appears to be that because `sphinx-build` is invoked as a script, it doesn't implicitly add `.` to sys.path.

It looks like the issue can be worked around by setting PYTHONPATH:

```
jaraco.tidelift main $ env PYTHONPATH=. .tox/docs/bin/sphinx-build docs build/sphinx/html
Running Sphinx v4.5.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: [config changed ('project')] 2 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                 
generating indices... genindex py-modindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in build/sphinx/html.
```

The reason it works with tox or rtd is because both environments install the target package before building the docs ([tox](https://github.com/jaraco/skeleton/blob/04fe68a96ee8e3d3ca521b4abbfe53203063f9d9/tox.ini#L13), [rtd](https://github.com/jaraco/skeleton/blob/04fe68a96ee8e3d3ca521b4abbfe53203063f9d9/.readthedocs.yml#L3-L4)).

I'd prefer not to add this ugly hack to the conf file of every project I maintain. I've worked hard to create this process that works reliably without the boilerplate hack.

I'd recommend instead that the the downstream packager be configured to install the package before building the docs or to employ the workaround of setting PYTHONPATH in order to fake having installed the package.

**Comment by kloczek** [comment]
> The issue doesn't occur when building docs using the tox environment:

Of course but assembly tox venv takes time and this patch guarantees that even without tox docuemtation will be always generated against source tree and not system installed `skeleton` module.

Outside pytjhon domain always when docuemtation is generated in source tree it is generated out of that tree and not against what is installed.
With that three lines patch replaces below
https://github.com/jaraco/skeleton/blob/04fe68a96ee8e3d3ca521b4abbfe53203063f9d9/tox.ini#L16-L23
If you will look on sphinx example copy,py file you can even find that what is in this patch should be done.
https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file so as you see that approach is even recommended.

**Comment by jaraco** [comment]
> With that three lines patch replaces below

It really doesn't, because it doesn't support lines 18 or 19 that instruct on which dependencies are needed to build the docs. It doesn't support line 20, which indicates in which directory the docs need to be built, and it doesn't support line 22, which indicates what parameters to pass to sphinx.

Moreover, the workaround you propose is inadequate, as it doesn't account for any dependencies. In the case of `jaraco.tidelift` (the distribution), Sphinx needs to be able to import `jaraco.tidelift` (the Python package). It won't be able to do this unless `jaraco.tidelift` is installed with its dependencies. The fact that your routine happens to have installed the dependencies but hasn't installed `jaraco.tidelift` means that routine isn't matching the expectation of skeleton-based projects.

Unfortunately, Python doesn't yet provide a standard way to declare docs building, so instead, projects based on skeleton use a pattern that supports standalone and RTD-based builds. These patterns define the interface expected for other builders.

It doesn't make sense to add a hack to this recipe in order to support a routine that doesn't meet that expectation (that the project is installed). Instead, I recommend that you adapt your routine to honor that expectation.
