### ISSUE TITLE
Add Pypy to GHA test matrix

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#63]
You can always add it to GHA test matrix. PyPy is surprisingly well supported, with all alphas and betas getting early support (and no fancy 'alpha' required like in cpython), i.e. right now `pypy-3.7`, `pypy-3.8` and `pypy-3.9`.

_Originally posted by @mgorny in https://github.com/jaraco/jaraco.collections/issues/7#issuecomment-1152030587_

**Comment by jaraco** [comment]
Good idea. I don’t want to multiply runs, though, so I’ll probably limit to just Linux and maybe only one or two pypy versions

**Comment by mgorny** [comment]
Sure (I'm not even sure if non-Linux targets are actually supported). As long as these are the newer versions, not `pypy-3.7` (that's being discontinued) ;-).
