### ISSUE TITLE
Make an asciinema recording

### ISSUE THREAD

**Issue by webknjaz** [jaraco/skeleton#7]
I think it would be great if you could use https://asciinema.org/ to record and share the workflow. It'd demonstrate things better.

You could then embed the thumbnail into README. Like this:
[![asciicast](https://asciinema.org/a/113463.svg)](https://asciinema.org/a/113463)

N.B. Since it's a terminal recording, it doesn't come with sound. So use `# comments` as a means to explain things.
```console
$ # doing X
$ ./X --smth
[..X-output-snip..]
$ # doing next step Y
[..snip..]
```

**Comment by jaraco** [comment]
Or maybe [termtosvg](/nbedos/termtosvg).

**Comment by webknjaz** [comment]
Wow! This looks even cooler! TIL

**Comment by jaraco** [comment]
In 814eb66, I've added a demonstration of one workflow - refreshing an already associated project with updates from the skeleton when there are no merge conflicts:

![refresh](https://raw.githubusercontent.com/jaraco/skeleton/master/docs/refresh.svg)

Tell me - does that begin to address the request? Are there other workflows you would like to see? What other changes would you like to see?

**Comment by jaraco** [comment]
I realize now I committed that capture to the skeleton, which I regret. Probably this project needs a separate branch for documentation about the skeleton itself... unless the content can be embedded entirely in the skeleton.md file.

**Comment by webknjaz** [comment]
Well, technically you can embed base64-encoded images in HTML `<img>` which also works for MD.

**Comment by webknjaz** [comment]
As for the workflow, it's probably better to use full git commands in that recording because those `gh://` shortcuts are specific to your machine. Also, it'd be interesting to see adding a subtree into an existing project.

**Comment by webknjaz** [comment]
Oh, and since there are no subtitles, it'd be great to see a comment starting with `#` before each command.

**Comment by jaraco** [comment]
> better to use full git commands

Yeah, good point. What do you think of instead including the detail that explains why that works, i.e. 

```
~ $ git config --get url.https://github.com/.insteadof                                                                                                              
gh://
```

That would allow the user to have a hint as to why it works, but also expose them to the feature if they're unfamiliar?

**Comment by webknjaz** [comment]
Well, that would introduce them to this feature. But then, it'll really confuse newbies as Git is known to have a high entry barrier.
I think this solely depends on the [target audience]. So specify the desired watcher level and stick with it.

[target audience]: https://twitter.com/b0rk/status/1262415197345636353

**Comment by jaraco** [comment]
One issue that's come up since this change is that the animation gets included with all downstream consumers of the skeleton. I think I'd like to create a separate branch of the repo for skeleton-specific documentation.

**Comment by jaraco** [comment]
I've cherry-picked the commit onto the gh-pages branch. Not sure if that's the best location, but I'm thinking it might be valuable at some point.

![demo](https://raw.githubusercontent.com/jaraco/skeleton/gh-pages/docs/refresh.svg)

Now I'll remove the file from the skeleton itself.

**Comment by jaraco** [comment]
Closing as complete (enough, for now).
