### ISSUE TITLE
Remove copyright notice

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#78]
After reading [this article](https://opensource.com/article/20/10/copyright-notices-open-source-software), I'm more convinced that a copyright notice is unnecessary and a nuisance (redundant and inconsistent to the data tracked in the source history).

**Comment by jaraco** [comment]
The annoying thing is that the outdated LICENSE file makes reference to the "above copyright", so it's not obvious what happens to the license if the copyright notice is removed.

I looked around for a copyright-agnostic license, but found [mostly unhelpful information](https://stackoverflow.com/questions/4158269/open-source-license-without-copyright-notice-reproduction-requirement).

I did find another project [dealing with the same concern](https://github.com/dtolnay/syn/issues/613) and settling on omitting the copyright notice.

Given the prior art, I'm going with that approach.

**Comment by jayaddison** [comment]
Thanks for this context @jaraco (I've arrived here from jaraco/inflect#197).

The article mentioned links to another item, https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects - and the suggestions there tend to resonate more strongly with me than the opensource.com article.
